// Auto-generated from @raycast/api Icon enum.
// Do not edit manually.

export const RAYCAST_ICON_NAMES = [
  'AddPerson',
  'Airplane',
  'AirplaneFilled',
  'AirplaneLanding',
  'AirplaneTakeoff',
  'Airpods',
  'Alarm',
  'AlarmRinging',
  'AlignCentre',
  'AlignLeft',
  'AlignRight',
  'AmericanFootball',
  'Anchor',
  'AppWindow',
  'AppWindowGrid2x2',
  'AppWindowGrid3x3',
  'AppWindowList',
  'AppWindowSidebarLeft',
  'AppWindowSidebarRight',
  'ArrowClockwise',
  'ArrowCounterClockwise',
  'ArrowDown',
  'ArrowDownCircle',
  'ArrowDownCircleFilled',
  'ArrowLeft',
  'ArrowLeftCircle',
  'ArrowLeftCircleFilled',
  'ArrowNe',
  'ArrowRight',
  'ArrowRightCircle',
  'ArrowRightCircleFilled',
  'ArrowUp',
  'ArrowUpCircle',
  'ArrowUpCircleFilled',
  'ArrowsContract',
  'ArrowsExpand',
  'AtSymbol',
  'BandAid',
  'BankNote',
  'BarChart',
  'BarCode',
  'BathTub',
  'Battery',
  'BatteryCharging',
  'BatteryDisabled',
  'Bell',
  'BellDisabled',
  'Bike',
  'Binoculars',
  'Bird',
  'BlankDocument',
  'Bluetooth',
  'Boat',
  'Bold',
  'Bolt',
  'BoltDisabled',
  'Book',
  'Bookmark',
  'Box',
  'Brush',
  'Bubble',
  'Bug',
  'Building',
  'BulletPoints',
  'BullsEye',
  'BullsEyeMissed',
  'Buoy',
  'Calculator',
  'Calendar',
  'Camera',
  'Car',
  'Cart',
  'Cd',
  'Center',
  'Check',
  'CheckCircle',
  'CheckList',
  'CheckRosette',
  'Checkmark',
  'ChessPiece',
  'ChevronDown',
  'ChevronDownSmall',
  'ChevronLeft',
  'ChevronLeftSmall',
  'ChevronRight',
  'ChevronRightSmall',
  'ChevronUp',
  'ChevronUpDown',
  'ChevronUpSmall',
  'Circle',
  'CircleDisabled',
  'CircleEllipsis',
  'CircleFilled',
  'CircleProgress',
  'CircleProgress100',
  'CircleProgress25',
  'CircleProgress50',
  'CircleProgress75',
  'ClearFormatting',
  'Clipboard',
  'Clock',
  'Cloud',
  'CloudLightning',
  'CloudRain',
  'CloudSnow',
  'CloudSun',
  'Code',
  'CodeBlock',
  'Cog',
  'Coin',
  'Coins',
  'CommandSymbol',
  'Compass',
  'ComputerChip',
  'Contrast',
  'CopyClipboard',
  'CreditCard',
  'CricketBall',
  'Crop',
  'Crown',
  'Crypto',
  'DeleteDocument',
  'Desktop',
  'Devices',
  'Dna',
  'Document',
  'Dot',
  'Download',
  'Droplets',
  'Duplicate',
  'EditShape',
  'Eject',
  'Ellipsis',
  'EllipsisVertical',
  'Emoji',
  'EmojiSad',
  'Envelope',
  'Eraser',
  'ExclamationMark',
  'Exclamationmark',
  'Exclamationmark2',
  'Exclamationmark3',
  'Eye',
  'EyeDisabled',
  'EyeDropper',
  'Female',
  'FilmStrip',
  'Filter',
  'Finder',
  'Fingerprint',
  'Flag',
  'Folder',
  'Footprints',
  'Forward',
  'ForwardFilled',
  'FountainTip',
  'FullSignal',
  'GameController',
  'Gauge',
  'Gear',
  'Geopin',
  'Germ',
  'Gift',
  'Glasses',
  'Globe',
  'Goal',
  'Hammer',
  'HardDrive',
  'Hashtag',
  'Heading',
  'Headphones',
  'Heart',
  'HeartDisabled',
  'Heartbeat',
  'Highlight',
  'Hourglass',
  'House',
  'Humidity',
  'Image',
  'Important',
  'Info',
  'Italics',
  'Key',
  'Keyboard',
  'Layers',
  'Leaderboard',
  'Leaf',
  'LevelMeter',
  'LightBulb',
  'LightBulbOff',
  'LineChart',
  'Link',
  'List',
  'Livestream',
  'LivestreamDisabled',
  'Lock',
  'LockDisabled',
  'LockUnlocked',
  'Logout',
  'Lorry',
  'Lowercase',
  'MagnifyingGlass',
  'Male',
  'Map',
  'Mask',
  'Maximize',
  'MedicalSupport',
  'Megaphone',
  'MemoryChip',
  'MemoryStick',
  'Message',
  'Microphone',
  'MicrophoneDisabled',
  'Minimize',
  'Minus',
  'MinusCircle',
  'MinusCircleFilled',
  'Mobile',
  'Monitor',
  'Moon',
  'MoonDown',
  'MoonUp',
  'Moonrise',
  'Mountain',
  'Mouse',
  'Move',
  'Mug',
  'MugSteam',
  'Multiply',
  'Music',
  'Network',
  'NewDocument',
  'NewFolder',
  'Number00',
  'Number01',
  'Number02',
  'Number03',
  'Number04',
  'Number05',
  'Number06',
  'Number07',
  'Number08',
  'Number09',
  'Number10',
  'Number11',
  'Number12',
  'Number13',
  'Number14',
  'Number15',
  'Number16',
  'Number17',
  'Number18',
  'Number19',
  'Number20',
  'Number21',
  'Number22',
  'Number23',
  'Number24',
  'Number25',
  'Number26',
  'Number27',
  'Number28',
  'Number29',
  'Number30',
  'Number31',
  'Number32',
  'Number33',
  'Number34',
  'Number35',
  'Number36',
  'Number37',
  'Number38',
  'Number39',
  'Number40',
  'Number41',
  'Number42',
  'Number43',
  'Number44',
  'Number45',
  'Number46',
  'Number47',
  'Number48',
  'Number49',
  'Number50',
  'Number51',
  'Number52',
  'Number53',
  'Number54',
  'Number55',
  'Number56',
  'Number57',
  'Number58',
  'Number59',
  'Number60',
  'Number61',
  'Number62',
  'Number63',
  'Number64',
  'Number65',
  'Number66',
  'Number67',
  'Number68',
  'Number69',
  'Number70',
  'Number71',
  'Number72',
  'Number73',
  'Number74',
  'Number75',
  'Number76',
  'Number77',
  'Number78',
  'Number79',
  'Number80',
  'Number81',
  'Number82',
  'Number83',
  'Number84',
  'Number85',
  'Number86',
  'Number87',
  'Number88',
  'Number89',
  'Number90',
  'Number91',
  'Number92',
  'Number93',
  'Number94',
  'Number95',
  'Number96',
  'Number97',
  'Number98',
  'Number99',
  'NumberList',
  'Paperclip',
  'Paragraph',
  'Patch',
  'Pause',
  'PauseFilled',
  'Pencil',
  'Person',
  'PersonCircle',
  'PersonLines',
  'Phone',
  'PhoneRinging',
  'PieChart',
  'Pill',
  'Pin',
  'PinDisabled',
  'Play',
  'PlayFilled',
  'Plug',
  'Plus',
  'PlusCircle',
  'PlusCircleFilled',
  'PlusMinusDivideMultiply',
  'PlusSquare',
  'PlusTopRightSquare',
  'Power',
  'Print',
  'QuestionMark',
  'QuestionMarkCircle',
  'Quicklink',
  'QuotationMarks',
  'QuoteBlock',
  'Racket',
  'Raindrop',
  'RaycastLogoNeg',
  'RaycastLogoPos',
  'Receipt',
  'Redo',
  'RemovePerson',
  'Repeat',
  'Replace',
  'ReplaceOne',
  'Reply',
  'Rewind',
  'RewindFilled',
  'Rocket',
  'Rosette',
  'RotateAntiClockwise',
  'RotateClockwise',
  'Rss',
  'Ruler',
  'SaveDocument',
  'Shield',
  'ShortParagraph',
  'Shuffle',
  'Sidebar',
  'Signal0',
  'Signal1',
  'Signal2',
  'Signal3',
  'Snippets',
  'Snowflake',
  'SoccerBall',
  'Speaker',
  'SpeakerDown',
  'SpeakerHigh',
  'SpeakerLow',
  'SpeakerOff',
  'SpeakerOn',
  'SpeakerUp',
  'SpeechBubble',
  'SpeechBubbleActive',
  'SpeechBubbleImportant',
  'SquareEllipsis',
  'StackedBars1',
  'StackedBars2',
  'StackedBars3',
  'StackedBars4',
  'Star',
  'StarCircle',
  'StarDisabled',
  'Stars',
  'Stop',
  'StopFilled',
  'Stopwatch',
  'Store',
  'StrikeThrough',
  'Sun',
  'Sunrise',
  'Swatch',
  'Switch',
  'Syringe',
  'Tack',
  'TackDisabled',
  'Tag',
  'Temperature',
  'TennisBall',
  'Terminal',
  'Text',
  'TextCursor',
  'TextInput',
  'TextSelection',
  'ThumbsDown',
  'ThumbsDownFilled',
  'ThumbsUp',
  'ThumbsUpFilled',
  'Ticket',
  'Torch',
  'Train',
  'Trash',
  'Tray',
  'Tree',
  'Trophy',
  'TwoPeople',
  'Umbrella',
  'Underline',
  'Undo',
  'Upload',
  'Uppercase',
  'Video',
  'VideoDisabled',
  'Wallet',
  'Wand',
  'Warning',
  'Waveform',
  'Weights',
  'Wifi',
  'WifiDisabled',
  'Wind',
  'Window',
  'Windsock',
  'WrenchScrewdriver',
  'WristWatch',
  'XMarkCircle',
  'XMarkCircleFilled',
  'XMarkCircleHalfDash',
  'XMarkTopRightSquare',
  'Xmark',
  'TwoArrowsClockwise',
  'EyeSlash',
  'SpeakerArrowDown',
  'SpeakerArrowUp',
  'SpeakerSlash',
  'TextDocument',
  'XmarkCircle',
] as const;

export type RaycastIconName = typeof RAYCAST_ICON_NAMES[number];

const RAYCAST_ICON_VALUE_NAME_ENTRIES: Array<[string, RaycastIconName]> = [
  ['add-person-16', 'AddPerson'],
  ['airplane-16', 'Airplane'],
  ['airplane-filled-16', 'AirplaneFilled'],
  ['airplane-landing-16', 'AirplaneLanding'],
  ['airplane-takeoff-16', 'AirplaneTakeoff'],
  ['airpods-16', 'Airpods'],
  ['alarm-16', 'Alarm'],
  ['alarm-ringing-16', 'AlarmRinging'],
  ['align-centre-16', 'AlignCentre'],
  ['align-left-16', 'AlignLeft'],
  ['align-right-16', 'AlignRight'],
  ['american-football-16', 'AmericanFootball'],
  ['anchor-16', 'Anchor'],
  ['app-window-16', 'AppWindow'],
  ['app-window-grid-2x2-16', 'AppWindowGrid2x2'],
  ['app-window-grid-3x3-16', 'AppWindowGrid3x3'],
  ['app-window-list-16', 'AppWindowList'],
  ['app-window-sidebar-left-16', 'AppWindowSidebarLeft'],
  ['app-window-sidebar-right-16', 'AppWindowSidebarRight'],
  ['arrow-clockwise-16', 'ArrowClockwise'],
  ['arrow-counter-clockwise-16', 'ArrowCounterClockwise'],
  ['arrow-down-16', 'ArrowDown'],
  ['arrow-down-circle-16', 'ArrowDownCircle'],
  ['arrow-down-circle-filled-16', 'ArrowDownCircleFilled'],
  ['arrow-left-16', 'ArrowLeft'],
  ['arrow-left-circle-16', 'ArrowLeftCircle'],
  ['arrow-left-circle-filled-16', 'ArrowLeftCircleFilled'],
  ['arrow-ne-16', 'ArrowNe'],
  ['arrow-right-16', 'ArrowRight'],
  ['arrow-right-circle-16', 'ArrowRightCircle'],
  ['arrow-right-circle-filled-16', 'ArrowRightCircleFilled'],
  ['arrow-up-16', 'ArrowUp'],
  ['arrow-up-circle-16', 'ArrowUpCircle'],
  ['arrow-up-circle-filled-16', 'ArrowUpCircleFilled'],
  ['arrows-contract-16', 'ArrowsContract'],
  ['arrows-expand-16', 'ArrowsExpand'],
  ['at-symbol-16', 'AtSymbol'],
  ['band-aid-16', 'BandAid'],
  ['bank-note-16', 'BankNote'],
  ['bar-chart-16', 'BarChart'],
  ['bar-code-16', 'BarCode'],
  ['bath-tub-16', 'BathTub'],
  ['battery-16', 'Battery'],
  ['battery-charging-16', 'BatteryCharging'],
  ['battery-disabled-16', 'BatteryDisabled'],
  ['bell-16', 'Bell'],
  ['bell-disabled-16', 'BellDisabled'],
  ['bike-16', 'Bike'],
  ['binoculars-16', 'Binoculars'],
  ['bird-16', 'Bird'],
  ['blank-document-16', 'BlankDocument'],
  ['bluetooth-16', 'Bluetooth'],
  ['boat-16', 'Boat'],
  ['bold-16', 'Bold'],
  ['bolt-16', 'Bolt'],
  ['bolt-disabled-16', 'BoltDisabled'],
  ['book-16', 'Book'],
  ['bookmark-16', 'Bookmark'],
  ['box-16', 'Box'],
  ['brush-16', 'Brush'],
  ['speech-bubble-16', 'Bubble'],
  ['bug-16', 'Bug'],
  ['building-16', 'Building'],
  ['bullet-points-16', 'BulletPoints'],
  ['bulls-eye-16', 'BullsEye'],
  ['bulls-eye-missed-16', 'BullsEyeMissed'],
  ['buoy-16', 'Buoy'],
  ['calculator-16', 'Calculator'],
  ['calendar-16', 'Calendar'],
  ['camera-16', 'Camera'],
  ['car-16', 'Car'],
  ['cart-16', 'Cart'],
  ['cd-16', 'Cd'],
  ['center-16', 'Center'],
  ['check-16', 'Check'],
  ['check-circle-16', 'CheckCircle'],
  ['check-list-16', 'CheckList'],
  ['check-rosette-16', 'CheckRosette'],
  ['checkmark-16', 'Checkmark'],
  ['chess-piece-16', 'ChessPiece'],
  ['chevron-down-16', 'ChevronDown'],
  ['chevron-down-small-16', 'ChevronDownSmall'],
  ['chevron-left-16', 'ChevronLeft'],
  ['chevron-left-small-16', 'ChevronLeftSmall'],
  ['chevron-right-16', 'ChevronRight'],
  ['chevron-right-small-16', 'ChevronRightSmall'],
  ['chevron-up-16', 'ChevronUp'],
  ['chevron-up-down-16', 'ChevronUpDown'],
  ['chevron-up-small-16', 'ChevronUpSmall'],
  ['circle-16', 'Circle'],
  ['circle-disabled-16', 'CircleDisabled'],
  ['circle-ellipsis-16', 'CircleEllipsis'],
  ['circle-filled-16', 'CircleFilled'],
  ['circle-progress-16', 'CircleProgress'],
  ['circle-progress-100-16', 'CircleProgress100'],
  ['circle-progress-25-16', 'CircleProgress25'],
  ['circle-progress-50-16', 'CircleProgress50'],
  ['circle-progress-75-16', 'CircleProgress75'],
  ['clear-formatting-16', 'ClearFormatting'],
  ['copy-clipboard-16', 'Clipboard'],
  ['clock-16', 'Clock'],
  ['cloud-16', 'Cloud'],
  ['cloud-lightning-16', 'CloudLightning'],
  ['cloud-rain-16', 'CloudRain'],
  ['cloud-snow-16', 'CloudSnow'],
  ['cloud-sun-16', 'CloudSun'],
  ['code-16', 'Code'],
  ['code-block-16', 'CodeBlock'],
  ['cog-16', 'Cog'],
  ['coin-16', 'Coin'],
  ['coins-16', 'Coins'],
  ['command-symbol-16', 'CommandSymbol'],
  ['compass-16', 'Compass'],
  ['computer-chip-16', 'ComputerChip'],
  ['contrast-16', 'Contrast'],
  ['copy-clipboard-16', 'CopyClipboard'],
  ['credit-card-16', 'CreditCard'],
  ['cricket-ball-16', 'CricketBall'],
  ['crop-16', 'Crop'],
  ['crown-16', 'Crown'],
  ['crypto-16', 'Crypto'],
  ['delete-document-16', 'DeleteDocument'],
  ['desktop-16', 'Desktop'],
  ['devices-16', 'Devices'],
  ['dna-16', 'Dna'],
  ['blank-document-16', 'Document'],
  ['dot-16', 'Dot'],
  ['download-16', 'Download'],
  ['droplets-16', 'Droplets'],
  ['duplicate-16', 'Duplicate'],
  ['edit-shape-16', 'EditShape'],
  ['eject-16', 'Eject'],
  ['ellipsis-16', 'Ellipsis'],
  ['ellipsis-vertical-16', 'EllipsisVertical'],
  ['emoji-16', 'Emoji'],
  ['emoji-sad-16', 'EmojiSad'],
  ['envelope-16', 'Envelope'],
  ['eraser-16', 'Eraser'],
  ['important-01-16', 'ExclamationMark'],
  ['exclamationmark-16', 'Exclamationmark'],
  ['exclamationmark-2-16', 'Exclamationmark2'],
  ['exclamationmark-3-16', 'Exclamationmark3'],
  ['eye-16', 'Eye'],
  ['eye-disabled-16', 'EyeDisabled'],
  ['eye-dropper-16', 'EyeDropper'],
  ['female-16', 'Female'],
  ['film-strip-16', 'FilmStrip'],
  ['filter-16', 'Filter'],
  ['finder-16', 'Finder'],
  ['fingerprint-16', 'Fingerprint'],
  ['flag-16', 'Flag'],
  ['folder-16', 'Folder'],
  ['footprints-16', 'Footprints'],
  ['forward-16', 'Forward'],
  ['forward-filled-16', 'ForwardFilled'],
  ['fountain-tip-16', 'FountainTip'],
  ['full-signal-16', 'FullSignal'],
  ['game-controller-16', 'GameController'],
  ['gauge-16', 'Gauge'],
  ['cog-16', 'Gear'],
  ['geopin-16', 'Geopin'],
  ['germ-16', 'Germ'],
  ['gift-16', 'Gift'],
  ['glasses-16', 'Glasses'],
  ['globe-01-16', 'Globe'],
  ['goal-16', 'Goal'],
  ['hammer-16', 'Hammer'],
  ['hard-drive-16', 'HardDrive'],
  ['hashtag-16', 'Hashtag'],
  ['heading-16', 'Heading'],
  ['headphones-16', 'Headphones'],
  ['heart-16', 'Heart'],
  ['heart-disabled-16', 'HeartDisabled'],
  ['heartbeat-16', 'Heartbeat'],
  ['highlight-16', 'Highlight'],
  ['hourglass-16', 'Hourglass'],
  ['house-16', 'House'],
  ['humidity-16', 'Humidity'],
  ['image-16', 'Image'],
  ['important-01-16', 'Important'],
  ['info-01-16', 'Info'],
  ['italics-16', 'Italics'],
  ['key-16', 'Key'],
  ['keyboard-16', 'Keyboard'],
  ['layers-16', 'Layers'],
  ['leaderboard-16', 'Leaderboard'],
  ['leaf-16', 'Leaf'],
  ['signal-2-16', 'LevelMeter'],
  ['light-bulb-16', 'LightBulb'],
  ['light-bulb-off-16', 'LightBulbOff'],
  ['line-chart-16', 'LineChart'],
  ['link-16', 'Link'],
  ['app-window-list-16', 'List'],
  ['livestream-01-16', 'Livestream'],
  ['livestream-disabled-01-16', 'LivestreamDisabled'],
  ['lock-16', 'Lock'],
  ['lock-disabled-16', 'LockDisabled'],
  ['lock-unlocked-16', 'LockUnlocked'],
  ['logout-16', 'Logout'],
  ['lorry-16', 'Lorry'],
  ['lowercase-16', 'Lowercase'],
  ['magnifying-glass-16', 'MagnifyingGlass'],
  ['male-16', 'Male'],
  ['map-16', 'Map'],
  ['mask-16', 'Mask'],
  ['maximize-16', 'Maximize'],
  ['medical-support-16', 'MedicalSupport'],
  ['megaphone-16', 'Megaphone'],
  ['computer-chip-16', 'MemoryChip'],
  ['memory-stick-16', 'MemoryStick'],
  ['speech-bubble-16', 'Message'],
  ['microphone-16', 'Microphone'],
  ['microphone-disabled-16', 'MicrophoneDisabled'],
  ['minimize-16', 'Minimize'],
  ['minus-16', 'Minus'],
  ['minus-circle-16', 'MinusCircle'],
  ['minus-circle-filled-16', 'MinusCircleFilled'],
  ['mobile-16', 'Mobile'],
  ['monitor-16', 'Monitor'],
  ['moon-16', 'Moon'],
  ['moon-down-16', 'MoonDown'],
  ['moon-up-16', 'MoonUp'],
  ['moonrise-16', 'Moonrise'],
  ['mountain-16', 'Mountain'],
  ['mouse-16', 'Mouse'],
  ['move-16', 'Move'],
  ['mug-16', 'Mug'],
  ['mug-steam-16', 'MugSteam'],
  ['multiply-16', 'Multiply'],
  ['music-16', 'Music'],
  ['network-16', 'Network'],
  ['new-document-16', 'NewDocument'],
  ['new-folder-16', 'NewFolder'],
  ['number-00-16', 'Number00'],
  ['number-01-16', 'Number01'],
  ['number-02-16', 'Number02'],
  ['number-03-16', 'Number03'],
  ['number-04-16', 'Number04'],
  ['number-05-16', 'Number05'],
  ['number-06-16', 'Number06'],
  ['number-07-16', 'Number07'],
  ['number-08-16', 'Number08'],
  ['number-09-16', 'Number09'],
  ['number-10-16', 'Number10'],
  ['number-11-16', 'Number11'],
  ['number-12-16', 'Number12'],
  ['number-13-16', 'Number13'],
  ['number-14-16', 'Number14'],
  ['number-15-16', 'Number15'],
  ['number-16-16', 'Number16'],
  ['number-17-16', 'Number17'],
  ['number-18-16', 'Number18'],
  ['number-19-16', 'Number19'],
  ['number-20-16', 'Number20'],
  ['number-21-16', 'Number21'],
  ['number-22-16', 'Number22'],
  ['number-23-16', 'Number23'],
  ['number-24-16', 'Number24'],
  ['number-25-16', 'Number25'],
  ['number-26-16', 'Number26'],
  ['number-27-16', 'Number27'],
  ['number-28-16', 'Number28'],
  ['number-29-16', 'Number29'],
  ['number-30-16', 'Number30'],
  ['number-31-16', 'Number31'],
  ['number-32-16', 'Number32'],
  ['number-33-16', 'Number33'],
  ['number-34-16', 'Number34'],
  ['number-35-16', 'Number35'],
  ['number-36-16', 'Number36'],
  ['number-37-16', 'Number37'],
  ['number-38-16', 'Number38'],
  ['number-39-16', 'Number39'],
  ['number-40-16', 'Number40'],
  ['number-41-16', 'Number41'],
  ['number-42-16', 'Number42'],
  ['number-43-16', 'Number43'],
  ['number-44-16', 'Number44'],
  ['number-45-16', 'Number45'],
  ['number-46-16', 'Number46'],
  ['number-47-16', 'Number47'],
  ['number-48-16', 'Number48'],
  ['number-49-16', 'Number49'],
  ['number-50-16', 'Number50'],
  ['number-51-16', 'Number51'],
  ['number-52-16', 'Number52'],
  ['number-53-16', 'Number53'],
  ['number-54-16', 'Number54'],
  ['number-55-16', 'Number55'],
  ['number-56-16', 'Number56'],
  ['number-57-16', 'Number57'],
  ['number-58-16', 'Number58'],
  ['number-59-16', 'Number59'],
  ['number-60-16', 'Number60'],
  ['number-61-16', 'Number61'],
  ['number-62-16', 'Number62'],
  ['number-63-16', 'Number63'],
  ['number-64-16', 'Number64'],
  ['number-65-16', 'Number65'],
  ['number-66-16', 'Number66'],
  ['number-67-16', 'Number67'],
  ['number-68-16', 'Number68'],
  ['number-69-16', 'Number69'],
  ['number-70-16', 'Number70'],
  ['number-71-16', 'Number71'],
  ['number-72-16', 'Number72'],
  ['number-73-16', 'Number73'],
  ['number-74-16', 'Number74'],
  ['number-75-16', 'Number75'],
  ['number-76-16', 'Number76'],
  ['number-77-16', 'Number77'],
  ['number-78-16', 'Number78'],
  ['number-79-16', 'Number79'],
  ['number-80-16', 'Number80'],
  ['number-81-16', 'Number81'],
  ['number-82-16', 'Number82'],
  ['number-83-16', 'Number83'],
  ['number-84-16', 'Number84'],
  ['number-85-16', 'Number85'],
  ['number-86-16', 'Number86'],
  ['number-87-16', 'Number87'],
  ['number-88-16', 'Number88'],
  ['number-89-16', 'Number89'],
  ['number-90-16', 'Number90'],
  ['number-91-16', 'Number91'],
  ['number-92-16', 'Number92'],
  ['number-93-16', 'Number93'],
  ['number-94-16', 'Number94'],
  ['number-95-16', 'Number95'],
  ['number-96-16', 'Number96'],
  ['number-97-16', 'Number97'],
  ['number-98-16', 'Number98'],
  ['number-99-16', 'Number99'],
  ['number-list-16', 'NumberList'],
  ['paperclip-16', 'Paperclip'],
  ['paragraph-16', 'Paragraph'],
  ['patch-16', 'Patch'],
  ['pause-16', 'Pause'],
  ['pause-filled-16', 'PauseFilled'],
  ['pencil-16', 'Pencil'],
  ['person-16', 'Person'],
  ['person-circle-16', 'PersonCircle'],
  ['person-lines-16', 'PersonLines'],
  ['phone-16', 'Phone'],
  ['phone-ringing-16', 'PhoneRinging'],
  ['pie-chart-16', 'PieChart'],
  ['pill-16', 'Pill'],
  ['pin-16', 'Pin'],
  ['pin-disabled-16', 'PinDisabled'],
  ['play-16', 'Play'],
  ['play-filled-16', 'PlayFilled'],
  ['plug-16', 'Plug'],
  ['plus-16', 'Plus'],
  ['plus-circle-16', 'PlusCircle'],
  ['plus-circle-filled-16', 'PlusCircleFilled'],
  ['plus-minus-divide-multiply-16', 'PlusMinusDivideMultiply'],
  ['plus-square-16', 'PlusSquare'],
  ['plus-top-right-square-16', 'PlusTopRightSquare'],
  ['power-16', 'Power'],
  ['print-16', 'Print'],
  ['question-mark-circle-16', 'QuestionMark'],
  ['question-mark-circle-16', 'QuestionMarkCircle'],
  ['quicklink-16', 'Quicklink'],
  ['quotation-marks-16', 'QuotationMarks'],
  ['quote-block-16', 'QuoteBlock'],
  ['racket-16', 'Racket'],
  ['raindrop-16', 'Raindrop'],
  ['raycast-logo-neg-16', 'RaycastLogoNeg'],
  ['raycast-logo-pos-16', 'RaycastLogoPos'],
  ['receipt-16', 'Receipt'],
  ['redo-16', 'Redo'],
  ['remove-person-16', 'RemovePerson'],
  ['repeat-16', 'Repeat'],
  ['replace-16', 'Replace'],
  ['replace-one-16', 'ReplaceOne'],
  ['reply-16', 'Reply'],
  ['rewind-16', 'Rewind'],
  ['rewind-filled-16', 'RewindFilled'],
  ['rocket-16', 'Rocket'],
  ['rosette-16', 'Rosette'],
  ['rotate-anti-clockwise-16', 'RotateAntiClockwise'],
  ['rotate-clockwise-16', 'RotateClockwise'],
  ['rss-16', 'Rss'],
  ['ruler-16', 'Ruler'],
  ['save-document-16', 'SaveDocument'],
  ['shield-01-16', 'Shield'],
  ['short-paragraph-16', 'ShortParagraph'],
  ['shuffle-16', 'Shuffle'],
  ['app-window-sidebar-right-16', 'Sidebar'],
  ['signal-0-16', 'Signal0'],
  ['signal-1-16', 'Signal1'],
  ['signal-2-16', 'Signal2'],
  ['signal-3-16', 'Signal3'],
  ['snippets-16', 'Snippets'],
  ['snowflake-16', 'Snowflake'],
  ['soccer-ball-16', 'SoccerBall'],
  ['speaker-16', 'Speaker'],
  ['speaker-down-16', 'SpeakerDown'],
  ['speaker-high-16', 'SpeakerHigh'],
  ['speaker-low-16', 'SpeakerLow'],
  ['speaker-off-16', 'SpeakerOff'],
  ['speaker-on-16', 'SpeakerOn'],
  ['speaker-up-16', 'SpeakerUp'],
  ['speech-bubble-16', 'SpeechBubble'],
  ['speech-bubble-active-16', 'SpeechBubbleActive'],
  ['speech-bubble-important-16', 'SpeechBubbleImportant'],
  ['square-ellipsis-16', 'SquareEllipsis'],
  ['stacked-bars-1-16', 'StackedBars1'],
  ['stacked-bars-2-16', 'StackedBars2'],
  ['stacked-bars-3-16', 'StackedBars3'],
  ['stacked-bars-4-16', 'StackedBars4'],
  ['star-16', 'Star'],
  ['star-circle-16', 'StarCircle'],
  ['star-disabled-16', 'StarDisabled'],
  ['stars-16', 'Stars'],
  ['stop-16', 'Stop'],
  ['stop-filled-16', 'StopFilled'],
  ['stopwatch-16', 'Stopwatch'],
  ['store-16', 'Store'],
  ['strike-through-16', 'StrikeThrough'],
  ['sun-16', 'Sun'],
  ['sunrise-16', 'Sunrise'],
  ['swatch-16', 'Swatch'],
  ['switch-16', 'Switch'],
  ['syringe-16', 'Syringe'],
  ['tack-16', 'Tack'],
  ['tack-disabled-16', 'TackDisabled'],
  ['tag-16', 'Tag'],
  ['temperature-16', 'Temperature'],
  ['tennis-ball-16', 'TennisBall'],
  ['terminal-16', 'Terminal'],
  ['text-16', 'Text'],
  ['text-cursor-16', 'TextCursor'],
  ['text-input-16', 'TextInput'],
  ['text-selection-16', 'TextSelection'],
  ['thumbs-down-16', 'ThumbsDown'],
  ['thumbs-down-filled-16', 'ThumbsDownFilled'],
  ['thumbs-up-16', 'ThumbsUp'],
  ['thumbs-up-filled-16', 'ThumbsUpFilled'],
  ['ticket-16', 'Ticket'],
  ['torch-16', 'Torch'],
  ['train-16', 'Train'],
  ['trash-16', 'Trash'],
  ['tray-16', 'Tray'],
  ['tree-16', 'Tree'],
  ['trophy-16', 'Trophy'],
  ['two-people-16', 'TwoPeople'],
  ['umbrella-16', 'Umbrella'],
  ['underline-16', 'Underline'],
  ['undo-16', 'Undo'],
  ['upload-16', 'Upload'],
  ['uppercase-16', 'Uppercase'],
  ['video-16', 'Video'],
  ['video-disabled-16', 'VideoDisabled'],
  ['wallet-16', 'Wallet'],
  ['wand-16', 'Wand'],
  ['warning-16', 'Warning'],
  ['waveform-16', 'Waveform'],
  ['weights-16', 'Weights'],
  ['wifi-16', 'Wifi'],
  ['wifi-disabled-16', 'WifiDisabled'],
  ['wind-16', 'Wind'],
  ['app-window-16', 'Window'],
  ['windsock-16', 'Windsock'],
  ['wrench-screwdriver-16', 'WrenchScrewdriver'],
  ['wrist-watch-16', 'WristWatch'],
  ['x-mark-circle-16', 'XMarkCircle'],
  ['x-mark-circle-filled-16', 'XMarkCircleFilled'],
  ['x-mark-circle-half-dash-16', 'XMarkCircleHalfDash'],
  ['x-mark-top-right-square-16', 'XMarkTopRightSquare'],
  ['xmark-16', 'Xmark'],
  ['arrow-clockwise-16', 'TwoArrowsClockwise'],
  ['eye-disabled-16', 'EyeSlash'],
  ['speaker-down-16', 'SpeakerArrowDown'],
  ['speaker-up-16', 'SpeakerArrowUp'],
  ['speaker-off-16', 'SpeakerSlash'],
  ['blank-document-16', 'TextDocument'],
  ['x-mark-circle-16', 'XmarkCircle'],
];

export const RAYCAST_ICON_VALUE_TO_NAME: Record<string, RaycastIconName> = Object.fromEntries(RAYCAST_ICON_VALUE_NAME_ENTRIES);
