export type EmojiCategory =
  | 'Smileys'
  | 'People'
  | 'Animals'
  | 'Food'
  | 'Activities'
  | 'Travel'
  | 'Objects'
  | 'Symbols'
  | 'Flags'

export type EmojiEntry = {
  char: string
  name: string
  category: EmojiCategory
  keywords: string[]
}

function define(
  category: EmojiCategory,
  entries: Array<[char: string, name: string, ...keywords: string[]]>,
): EmojiEntry[] {
  return entries.map(([char, name, ...keywords]) => ({ char, name, category, keywords }))
}

export const EMOJI_CATEGORIES: readonly EmojiCategory[] = [
  'Smileys',
  'People',
  'Animals',
  'Food',
  'Activities',
  'Travel',
  'Objects',
  'Symbols',
  'Flags',
]

export const EMOJI_DATA: EmojiEntry[] = [
  ...define('Smileys', [
    ['😀', 'grinning face', 'happy', 'smile', 'joy', 'cheerful', 'positive', 'friendly', 'yellow', 'face', 'good', 'glad', 'yay'],
    ['😃', 'grinning face with big eyes', 'happy', 'excited', 'smile', 'joyful', 'bright', 'yellow', 'face', 'delighted', 'upbeat', 'pleased'],
    ['😄', 'grinning face with smiling eyes', 'laugh', 'lol', 'happy', 'smile', 'joy', 'fun', 'bright', 'yellow', 'face', 'cheery'],
    ['😁', 'beaming face with smiling eyes', 'grin', 'teeth', 'smile', 'excited', 'delight', 'yellow', 'face', 'very happy', 'yay'],
    ['😆', 'grinning squinting face', 'lol', 'laughing', 'funny', 'haha', 'joke', 'joy', 'face', 'yellow', 'comedy', 'lmao'],
    ['😅', 'grinning face with sweat', 'nervous laugh', 'awkward', 'whew', 'relief', 'sweat', 'face', 'yellow', 'oops', 'close call'],
    ['🤣', 'rolling on the floor laughing', 'rofl', 'lol', 'lmao', 'hilarious', 'funny', 'joke', 'cry laughing', 'face', 'comedy'],
    ['😂', 'face with tears of joy', 'lol', 'laugh', 'haha', 'funny', 'joy', 'tears', 'cry', 'face', 'meme'],
    ['🙂', 'slightly smiling face', 'smile', 'polite', 'nice', 'gentle', 'friendly', 'yellow', 'face', 'calm'],
    ['🙃', 'upside-down face', 'sarcasm', 'irony', 'silly', 'goofy', 'playful', 'flip', 'yellow', 'face'],
    ['😉', 'winking face', 'wink', 'flirt', 'joke', 'playful', 'tease', 'yellow', 'face', 'hint'],
    ['😊', 'smiling face with smiling eyes', 'happy', 'blush', 'warm', 'kind', 'sweet', 'friendly', 'yellow', 'face'],
    ['😇', 'smiling face with halo', 'angel', 'innocent', 'good', 'blessed', 'pure', 'holy', 'face', 'yellow'],
    ['🥰', 'smiling face with hearts', 'love', 'adore', 'affection', 'romance', 'cute', 'heart', 'crush', 'face'],
    ['😍', 'smiling face with heart eyes', 'love', 'heart eyes', 'crush', 'adore', 'romance', 'attracted', 'face'],
    ['🤩', 'star-struck', 'amazed', 'wow', 'excited', 'impressed', 'star eyes', 'fan', 'hype', 'face'],
    ['😘', 'face blowing a kiss', 'kiss', 'love', 'romance', 'affection', 'flirt', 'mwah', 'face'],
    ['😗', 'kissing face', 'kiss', 'peck', 'love', 'romance', 'face', 'affection'],
    ['😚', 'kissing face with closed eyes', 'kiss', 'love', 'romantic', 'sweet', 'affection', 'face'],
    ['😙', 'kissing face with smiling eyes', 'kiss', 'happy', 'love', 'affection', 'face', 'romance'],
    ['🥲', 'smiling face with tear', 'touched', 'emotional', 'happy cry', 'bittersweet', 'sad happy', 'face'],
    ['😋', 'face savoring food', 'yum', 'delicious', 'tasty', 'hungry', 'food', 'lick', 'face'],
    ['😛', 'face with tongue', 'silly', 'tease', 'playful', 'goofy', 'tongue out', 'face'],
    ['😜', 'winking face with tongue', 'silly', 'joking', 'tease', 'fun', 'goofy', 'face'],
    ['🤪', 'zany face', 'crazy', 'wild', 'goofy', 'chaotic', 'silly', 'weird', 'face'],
    ['😝', 'squinting face with tongue', 'funny', 'silly', 'joke', 'playful', 'tease', 'face'],
    ['🫠', 'melting face', 'hot', 'embarrassed', 'awkward', 'cringe', 'sweat', 'face', 'overwhelmed'],
    ['🤗', 'hugging face', 'hug', 'support', 'care', 'comfort', 'warmth', 'friendly', 'face'],
    ['🫡', 'saluting face', 'respect', 'sir', 'acknowledge', 'yes captain', 'military', 'face'],
    ['🤔', 'thinking face', 'hmm', 'question', 'ponder', 'consider', 'unsure', 'face', 'idea'],
    ['🫢', 'face with open eyes and hand over mouth', 'surprised', 'oops', 'shock', 'gasp', 'secret', 'face'],
    ['🤭', 'face with hand over mouth', 'giggle', 'oops', 'secret', 'cute', 'oopsie', 'face'],
    ['🤫', 'shushing face', 'quiet', 'shh', 'secret', 'silence', 'hush', 'face'],
    ['🤥', 'lying face', 'lie', 'dishonest', 'pinocchio', 'fake', 'sus', 'face'],
    ['😶', 'face without mouth', 'speechless', 'silent', 'blank', 'mute', 'face'],
    ['😐', 'neutral face', 'meh', 'indifferent', 'blank', 'neutral', 'face'],
    ['🫤', 'face with diagonal mouth', 'unsure', 'confused', 'meh', 'awkward', 'face'],
    ['😑', 'expressionless face', 'blank', 'deadpan', 'unimpressed', 'meh', 'face'],
    ['😬', 'grimacing face', 'awkward', 'yikes', 'cringe', 'nervous', 'teeth', 'face'],
    ['🙄', 'face with rolling eyes', 'eyeroll', 'annoyed', 'whatever', 'sarcasm', 'face'],
    ['😌', 'relieved face', 'calm', 'content', 'peaceful', 'relax', 'face'],
    ['😔', 'pensive face', 'sad', 'thinking', 'down', 'upset', 'face'],
    ['😪', 'sleepy face', 'sleepy', 'tired', 'drowsy', 'yawn', 'face'],
    ['🤤', 'drooling face', 'hungry', 'want', 'desire', 'food', 'crave', 'face'],
    ['😴', 'sleeping face', 'sleep', 'zzz', 'tired', 'nap', 'face'],
    ['😷', 'face with medical mask', 'mask', 'sick', 'health', 'doctor', 'face'],
    ['🤒', 'face with thermometer', 'sick', 'fever', 'ill', 'unwell', 'face'],
    ['🤕', 'face with head bandage', 'injured', 'hurt', 'ouch', 'pain', 'face'],
    ['🤢', 'nauseated face', 'sick', 'gross', 'disgust', 'vomit', 'face'],
    ['🤮', 'face vomiting', 'vomit', 'gross', 'sick', 'ill', 'face'],
    ['🤧', 'sneezing face', 'sneeze', 'cold', 'allergy', 'achoo', 'face'],
    ['🥵', 'hot face', 'hot', 'heat', 'sweat', 'summer', 'overheated', 'face'],
    ['🥶', 'cold face', 'cold', 'freezing', 'winter', 'chill', 'face'],
    ['🥴', 'woozy face', 'dizzy', 'drunk', 'confused', 'off', 'face'],
    ['😵', 'face with crossed-out eyes', 'dizzy', 'dead', 'knocked out', 'faint', 'face'],
    ['🤯', 'exploding head', 'mind blown', 'wow', 'shock', 'amazed', 'face'],
    ['🤠', 'cowboy hat face', 'cowboy', 'yeehaw', 'country', 'western', 'face'],
    ['🥳', 'partying face', 'party', 'celebrate', 'birthday', 'fun', 'face'],
    ['😎', 'smiling face with sunglasses', 'cool', 'chill', 'swag', 'sun', 'face', 'awesome'],
    ['🤓', 'nerd face', 'geek', 'smart', 'study', 'glasses', 'face'],
    ['🧐', 'face with monocle', 'inspect', 'fancy', 'curious', 'hmm', 'face'],
    ['😕', 'confused face', 'confused', 'huh', 'unsure', 'puzzled', 'face'],
    ['😟', 'worried face', 'worried', 'anxious', 'concern', 'stress', 'face'],
    ['🙁', 'slightly frowning face', 'sad', 'unhappy', 'down', 'face'],
    ['☹️', 'frowning face', 'sad', 'upset', 'unhappy', 'face'],
    ['😮', 'face with open mouth', 'surprised', 'wow', 'shock', 'gasp', 'face'],
    ['😯', 'hushed face', 'surprised', 'silent', 'wow', 'face'],
    ['😲', 'astonished face', 'shock', 'surprised', 'wow', 'face'],
    ['😳', 'flushed face', 'embarrassed', 'blush', 'shy', 'awkward', 'face'],
    ['🥺', 'pleading face', 'please', 'puppy eyes', 'beg', 'cute', 'face'],
    ['😦', 'frowning face with open mouth', 'anxious', 'concerned', 'worried', 'face'],
    ['😧', 'anguished face', 'pain', 'sad', 'worried', 'distress', 'face'],
    ['😨', 'fearful face', 'scared', 'fear', 'afraid', 'anxious', 'face'],
    ['😰', 'anxious face with sweat', 'nervous', 'stress', 'worry', 'sweat', 'face'],
    ['😥', 'sad but relieved face', 'relief', 'sad', 'whew', 'face'],
    ['😢', 'crying face', 'sad', 'cry', 'tears', 'upset', 'face'],
    ['😭', 'loudly crying face', 'sob', 'crying', 'tears', 'very sad', 'face'],
    ['😱', 'face screaming in fear', 'scared', 'scream', 'shock', 'horror', 'face'],
    ['😖', 'confounded face', 'frustrated', 'pain', 'annoyed', 'face'],
    ['😣', 'persevering face', 'struggling', 'stress', 'endure', 'face'],
    ['😞', 'disappointed face', 'sad', 'letdown', 'unhappy', 'face'],
    ['😓', 'downcast face with sweat', 'sad', 'stress', 'worry', 'face'],
    ['😩', 'weary face', 'tired', 'exhausted', 'ugh', 'done', 'face'],
    ['😫', 'tired face', 'exhausted', 'fatigue', 'drained', 'face'],
    ['🥱', 'yawning face', 'yawn', 'sleepy', 'bored', 'tired', 'face'],
    ['😤', 'face with steam from nose', 'angry', 'frustrated', 'mad', 'huff', 'face'],
    ['😡', 'pouting face', 'angry', 'mad', 'rage', 'annoyed', 'furious', 'face'],
    ['😠', 'angry face', 'angry', 'mad', 'upset', 'annoyed', 'face'],
    ['🤬', 'face with symbols on mouth', 'swear', 'curse', 'angry', 'rage', 'face'],
    ['😈', 'smiling face with horns', 'devil', 'mischief', 'evil', 'face'],
    ['👿', 'angry face with horns', 'devil', 'evil', 'angry', 'demon', 'face'],
    ['💀', 'skull', 'dead', 'death', 'bones', 'spooky', 'halloween'],
    ['☠️', 'skull and crossbones', 'danger', 'poison', 'pirate', 'death', 'warning'],
    ['💩', 'pile of poo', 'poop', 'shit', 'funny', 'crap', 'brown'],
    ['🤡', 'clown face', 'clown', 'circus', 'silly', 'joker', 'face'],
    ['👻', 'ghost', 'spooky', 'halloween', 'boo', 'spirit', 'white'],
    ['👽', 'alien', 'ufo', 'space', 'extraterrestrial', 'green'],
    ['👾', 'alien monster', 'game', 'retro', 'space invader', 'pixel'],
    ['🤖', 'robot', 'bot', 'ai', 'machine', 'tech', 'android'],
    ['😺', 'grinning cat', 'cat', 'happy', 'smile', 'pet', 'feline'],
    ['😸', 'grinning cat with smiling eyes', 'cat', 'happy', 'lol', 'pet'],
    ['😹', 'cat with tears of joy', 'cat', 'lol', 'laugh', 'pet'],
    ['😻', 'smiling cat with heart eyes', 'cat', 'love', 'pet', 'heart eyes'],
    ['😼', 'cat with wry smile', 'cat', 'smirk', 'pet', 'sly'],
    ['😽', 'kissing cat', 'cat', 'kiss', 'pet', 'love'],
    ['🙀', 'weary cat', 'cat', 'shock', 'scared', 'pet'],
    ['😿', 'crying cat', 'cat', 'sad', 'cry', 'pet'],
    ['😾', 'pouting cat', 'cat', 'angry', 'mad', 'pet'],
    ['❤️', 'red heart', 'love', 'heart', 'romance', 'affection', 'like', 'favorite'],
    ['🧡', 'orange heart', 'heart', 'love', 'care', 'warmth'],
    ['💛', 'yellow heart', 'heart', 'friendship', 'joy', 'care'],
    ['💚', 'green heart', 'heart', 'nature', 'healthy', 'growth'],
    ['💙', 'blue heart', 'heart', 'trust', 'calm', 'support'],
    ['💜', 'purple heart', 'heart', 'compassion', 'care', 'love'],
    ['🖤', 'black heart', 'heart', 'dark', 'goth', 'emo'],
    ['🤍', 'white heart', 'heart', 'pure', 'peace', 'clean'],
    ['🤎', 'brown heart', 'heart', 'earth', 'warm', 'support'],
    ['💔', 'broken heart', 'heartbreak', 'sad', 'breakup', 'pain'],
    ['❣️', 'heart exclamation', 'love', 'heart', 'exclamation', 'attention'],
    ['💕', 'two hearts', 'love', 'romance', 'affection', 'hearts'],
    ['💞', 'revolving hearts', 'love', 'hearts', 'romance', 'relationship'],
    ['💓', 'beating heart', 'heartbeat', 'love', 'heart', 'pulse'],
    ['💗', 'growing heart', 'love', 'heart', 'growing', 'romance'],
    ['💖', 'sparkling heart', 'love', 'heart', 'sparkle', 'shiny'],
    ['💘', 'heart with arrow', 'cupid', 'love', 'romance', 'crush'],
    ['💝', 'heart with ribbon', 'gift', 'love', 'present', 'heart'],
    ['💟', 'heart decoration', 'heart', 'symbol', 'love'],
  ]),
  ...define('People', [
    ['👍', 'thumbs up', 'thumb up', 'like', 'yes', 'approve', 'good', 'ok', 'cool', 'agree'],
    ['👎', 'thumbs down', 'dislike', 'no', 'bad', 'reject', 'boo'],
    ['👌', 'ok hand', 'ok', 'perfect', 'fine', 'good', 'agree'],
    ['👊', 'oncoming fist', 'fist bump', 'punch', 'bro', 'solid'],
    ['✊', 'raised fist', 'power', 'solidarity', 'protest', 'fist'],
    ['🤛', 'left-facing fist', 'fist bump', 'left fist', 'bro'],
    ['🤜', 'right-facing fist', 'fist bump', 'right fist', 'bro'],
    ['👏', 'clapping hands', 'clap', 'applause', 'bravo', 'well done'],
    ['🙌', 'raising hands', 'hooray', 'celebrate', 'praise', 'yay'],
    ['🫶', 'heart hands', 'love', 'support', 'care', 'heart'],
    ['👐', 'open hands', 'hug', 'open', 'welcome', 'hands'],
    ['🤲', 'palms up together', 'please', 'offering', 'prayer', 'hands'],
    ['🤝', 'handshake', 'deal', 'agreement', 'partnership', 'shake'],
    ['🙏', 'folded hands', 'pray', 'thanks', 'please', 'gratitude'],
    ['✍️', 'writing hand', 'write', 'note', 'sign', 'pen'],
    ['💅', 'nail polish', 'nails', 'beauty', 'self care', 'slay'],
    ['🤳', 'selfie', 'photo', 'camera', 'self portrait', 'phone'],
    ['💪', 'flexed biceps', 'strong', 'muscle', 'gym', 'power'],
    ['🦾', 'mechanical arm', 'robot arm', 'bionic', 'strength', 'cyborg'],
    ['🦿', 'mechanical leg', 'bionic leg', 'robot', 'cyborg'],
    ['🦵', 'leg', 'kick', 'walk', 'body', 'limb'],
    ['🦶', 'foot', 'feet', 'walk', 'step'],
    ['👂', 'ear', 'listen', 'hearing', 'sound'],
    ['🦻', 'ear with hearing aid', 'hearing aid', 'accessibility', 'listen'],
    ['👃', 'nose', 'smell', 'sniff', 'face'],
    ['🧠', 'brain', 'smart', 'mind', 'think', 'intelligence'],
    ['🫀', 'anatomical heart', 'heart organ', 'health', 'medical'],
    ['🫁', 'lungs', 'breath', 'respiratory', 'health'],
    ['🦷', 'tooth', 'dentist', 'teeth', 'dental'],
    ['🦴', 'bone', 'skeleton', 'orthopedic', 'body'],
    ['👀', 'eyes', 'look', 'watching', 'see', 'stare'],
    ['👁️', 'eye', 'look', 'watch', 'vision'],
    ['👅', 'tongue', 'taste', 'lick', 'mouth'],
    ['👄', 'mouth', 'lips', 'speak', 'kiss'],
    ['👶', 'baby', 'infant', 'child', 'newborn'],
    ['🧒', 'child', 'kid', 'young', 'boy', 'girl'],
    ['👦', 'boy', 'male child', 'kid'],
    ['👧', 'girl', 'female child', 'kid'],
    ['🧑', 'person', 'adult', 'human', 'someone'],
    ['👨', 'man', 'male', 'adult'],
    ['👩', 'woman', 'female', 'adult'],
    ['🧔', 'person beard', 'beard', 'facial hair', 'man'],
    ['👱', 'person blond hair', 'blond', 'hair', 'person'],
    ['👴', 'old man', 'elderly', 'grandpa', 'senior'],
    ['👵', 'old woman', 'elderly', 'grandma', 'senior'],
    ['🧓', 'older person', 'senior', 'elderly', 'old'],
    ['👮', 'police officer', 'cop', 'law', 'security'],
    ['🕵️', 'detective', 'spy', 'investigate', 'sleuth'],
    ['💂', 'guard', 'royal guard', 'security', 'soldier'],
    ['👷', 'construction worker', 'builder', 'helmet', 'work'],
    ['🤴', 'prince', 'royal', 'kingdom', 'crown'],
    ['👸', 'princess', 'royal', 'queen', 'crown'],
    ['👳', 'person wearing turban', 'turban', 'headwear', 'person'],
    ['👲', 'person with skullcap', 'cap', 'person'],
    ['🧕', 'woman with headscarf', 'hijab', 'headscarf', 'woman'],
    ['🤵', 'person in tuxedo', 'wedding', 'formal', 'suit'],
    ['👰', 'person with veil', 'bride', 'wedding', 'marriage'],
    ['🤰', 'pregnant woman', 'pregnant', 'baby', 'maternity'],
    ['🫃', 'pregnant man', 'pregnant', 'parenthood'],
    ['🫄', 'pregnant person', 'pregnant', 'parenthood'],
    ['🤱', 'breast-feeding', 'mother', 'baby', 'feeding'],
    ['👼', 'baby angel', 'angel', 'halo', 'baby'],
    ['🎅', 'santa claus', 'christmas', 'holiday', 'xmas'],
    ['🤶', 'mrs claus', 'christmas', 'holiday', 'xmas'],
    ['🧑‍🎄', 'mx claus', 'christmas', 'holiday', 'xmas'],
    ['🦸', 'superhero', 'hero', 'cape', 'power'],
    ['🦹', 'supervillain', 'villain', 'evil', 'cape'],
    ['🧙', 'mage', 'wizard', 'magic', 'sorcerer'],
    ['🧚', 'fairy', 'magic', 'fantasy', 'wings'],
    ['🧛', 'vampire', 'halloween', 'undead', 'fangs'],
    ['🧜', 'merperson', 'mermaid', 'ocean', 'myth'],
    ['🧝', 'elf', 'fantasy', 'myth', 'magic'],
    ['🧞', 'genie', 'wish', 'magic', 'lamp'],
    ['🧟', 'zombie', 'undead', 'halloween', 'horror'],
    ['💆', 'person getting massage', 'spa', 'relax', 'self care'],
    ['💇', 'person getting haircut', 'hair', 'salon', 'style'],
    ['🚶', 'person walking', 'walk', 'step', 'move'],
    ['🧍', 'person standing', 'stand', 'wait', 'still'],
    ['🧎', 'person kneeling', 'kneel', 'pose', 'ground'],
    ['🏃', 'person running', 'run', 'jog', 'fast', 'exercise'],
    ['💃', 'woman dancing', 'dance', 'party', 'fun'],
    ['🕺', 'man dancing', 'dance', 'party', 'fun'],
  ]),
  ...define('Animals', [
    ['🐶', 'dog face', 'dog', 'pet', 'puppy', 'animal'],
    ['🐱', 'cat face', 'cat', 'pet', 'kitty', 'animal'],
    ['🐭', 'mouse face', 'mouse', 'rodent', 'animal'],
    ['🐹', 'hamster face', 'hamster', 'pet', 'animal'],
    ['🐰', 'rabbit face', 'bunny', 'rabbit', 'animal'],
    ['🦊', 'fox', 'fox', 'animal', 'wild'],
    ['🐻', 'bear', 'bear', 'animal', 'wild'],
    ['🐼', 'panda', 'panda', 'animal', 'cute'],
    ['🐨', 'koala', 'koala', 'animal', 'australia'],
    ['🐯', 'tiger face', 'tiger', 'animal', 'wild'],
    ['🦁', 'lion', 'lion', 'animal', 'king'],
    ['🐮', 'cow face', 'cow', 'farm', 'animal'],
    ['🐷', 'pig face', 'pig', 'farm', 'animal'],
    ['🐸', 'frog', 'frog', 'animal', 'green'],
    ['🐵', 'monkey face', 'monkey', 'animal', 'primate'],
    ['🙈', 'see-no-evil monkey', 'monkey', 'evil', 'cute'],
    ['🙉', 'hear-no-evil monkey', 'monkey', 'evil', 'cute'],
    ['🙊', 'speak-no-evil monkey', 'monkey', 'evil', 'cute'],
    ['🐒', 'monkey', 'animal', 'primate', 'jungle'],
    ['🐔', 'chicken', 'bird', 'farm', 'animal'],
    ['🐧', 'penguin', 'penguin', 'bird', 'animal'],
    ['🐦', 'bird', 'bird', 'animal', 'fly'],
    ['🐤', 'baby chick', 'chick', 'bird', 'cute'],
    ['🦆', 'duck', 'duck', 'bird', 'animal'],
    ['🦅', 'eagle', 'eagle', 'bird', 'animal'],
    ['🦉', 'owl', 'owl', 'bird', 'animal', 'night'],
    ['🦇', 'bat', 'bat', 'animal', 'night', 'halloween'],
    ['🐺', 'wolf', 'wolf', 'animal', 'wild'],
    ['🐗', 'boar', 'boar', 'pig', 'animal'],
    ['🐴', 'horse face', 'horse', 'animal', 'stable'],
    ['🦄', 'unicorn', 'unicorn', 'magic', 'fantasy'],
    ['🐝', 'honeybee', 'bee', 'insect', 'honey'],
    ['🪲', 'beetle', 'bug', 'insect', 'animal'],
    ['🦋', 'butterfly', 'butterfly', 'insect', 'nature'],
    ['🐌', 'snail', 'snail', 'slow', 'animal'],
    ['🐞', 'lady beetle', 'ladybug', 'insect', 'bug'],
    ['🐜', 'ant', 'ant', 'insect', 'bug'],
    ['🪰', 'fly', 'fly', 'insect', 'bug'],
    ['🪱', 'worm', 'worm', 'insect', 'soil'],
    ['🐢', 'turtle', 'turtle', 'animal', 'slow'],
    ['🐍', 'snake', 'snake', 'animal', 'reptile'],
    ['🦎', 'lizard', 'lizard', 'reptile', 'animal'],
    ['🦂', 'scorpion', 'scorpion', 'animal', 'danger'],
    ['🦀', 'crab', 'crab', 'seafood', 'animal'],
    ['🐙', 'octopus', 'octopus', 'ocean', 'animal'],
    ['🦑', 'squid', 'squid', 'ocean', 'animal'],
    ['🐠', 'tropical fish', 'fish', 'ocean', 'animal'],
    ['🐳', 'spouting whale', 'whale', 'ocean', 'animal'],
    ['🦈', 'shark', 'shark', 'ocean', 'animal'],
  ]),
  ...define('Food', [
    ['🍎', 'red apple', 'apple', 'fruit', 'food', 'healthy'],
    ['🍌', 'banana', 'banana', 'fruit', 'food'],
    ['🍇', 'grapes', 'grape', 'fruit', 'food'],
    ['🍓', 'strawberry', 'strawberry', 'fruit', 'food'],
    ['🍒', 'cherries', 'cherry', 'fruit', 'food'],
    ['🍑', 'peach', 'peach', 'fruit', 'food'],
    ['🍍', 'pineapple', 'pineapple', 'fruit', 'food', 'tropical'],
    ['🥭', 'mango', 'mango', 'fruit', 'food'],
    ['🍉', 'watermelon', 'watermelon', 'fruit', 'food'],
    ['🥝', 'kiwi fruit', 'kiwi', 'fruit', 'food'],
    ['🍋', 'lemon', 'lemon', 'fruit', 'food', 'sour'],
    ['🍊', 'tangerine', 'orange', 'fruit', 'food'],
    ['🥑', 'avocado', 'avocado', 'food', 'healthy'],
    ['🍅', 'tomato', 'tomato', 'vegetable', 'food'],
    ['🥕', 'carrot', 'carrot', 'vegetable', 'food'],
    ['🌽', 'ear of corn', 'corn', 'vegetable', 'food'],
    ['🥦', 'broccoli', 'broccoli', 'vegetable', 'food'],
    ['🥬', 'leafy green', 'lettuce', 'vegetable', 'food'],
    ['🥔', 'potato', 'potato', 'vegetable', 'food'],
    ['🍆', 'eggplant', 'eggplant', 'vegetable', 'food'],
    ['🌶️', 'hot pepper', 'pepper', 'spicy', 'food'],
    ['🫑', 'bell pepper', 'pepper', 'vegetable', 'food'],
    ['🥒', 'cucumber', 'cucumber', 'vegetable', 'food'],
    ['🍞', 'bread', 'bread', 'food', 'bakery'],
    ['🥐', 'croissant', 'croissant', 'pastry', 'food'],
    ['🥖', 'baguette bread', 'baguette', 'bread', 'food'],
    ['🧀', 'cheese wedge', 'cheese', 'food', 'dairy'],
    ['🥚', 'egg', 'egg', 'food', 'breakfast'],
    ['🍳', 'cooking', 'fried egg', 'pan', 'breakfast', 'food'],
    ['🥓', 'bacon', 'bacon', 'breakfast', 'food'],
    ['🥞', 'pancakes', 'pancake', 'breakfast', 'food'],
    ['🧇', 'waffle', 'waffle', 'breakfast', 'food'],
    ['🍗', 'poultry leg', 'chicken', 'meat', 'food'],
    ['🍖', 'meat on bone', 'meat', 'food', 'bbq'],
    ['🌭', 'hot dog', 'hotdog', 'sausage', 'food'],
    ['🍔', 'hamburger', 'burger', 'food', 'fast food'],
    ['🍟', 'french fries', 'fries', 'food', 'snack'],
    ['🍕', 'pizza', 'pizza', 'food', 'slice'],
    ['🥪', 'sandwich', 'sandwich', 'food', 'lunch'],
    ['🌮', 'taco', 'taco', 'food', 'mexican'],
    ['🌯', 'burrito', 'burrito', 'food', 'mexican'],
    ['🍜', 'steaming bowl', 'ramen', 'noodles', 'soup', 'food'],
    ['🍣', 'sushi', 'sushi', 'food', 'japanese'],
    ['🍱', 'bento box', 'bento', 'lunch', 'food'],
    ['🍛', 'curry rice', 'curry', 'rice', 'food'],
    ['🍚', 'cooked rice', 'rice', 'food'],
    ['🍦', 'soft ice cream', 'ice cream', 'dessert', 'food'],
    ['🍩', 'doughnut', 'donut', 'dessert', 'food'],
    ['🍪', 'cookie', 'cookie', 'dessert', 'food'],
    ['🎂', 'birthday cake', 'cake', 'birthday', 'dessert'],
    ['🍫', 'chocolate bar', 'chocolate', 'dessert', 'sweet'],
    ['🍿', 'popcorn', 'popcorn', 'movie', 'snack'],
    ['☕', 'hot beverage', 'coffee', 'tea', 'drink'],
    ['🧋', 'bubble tea', 'boba', 'tea', 'drink'],
    ['🥤', 'cup with straw', 'soda', 'drink', 'juice'],
    ['🧃', 'beverage box', 'juice box', 'drink'],
  ]),
  ...define('Activities', [
    ['⚽', 'soccer ball', 'football', 'soccer', 'sport', 'game'],
    ['🏀', 'basketball', 'basketball', 'sport', 'game'],
    ['🏈', 'american football', 'football', 'nfl', 'sport'],
    ['⚾', 'baseball', 'baseball', 'sport', 'game'],
    ['🥎', 'softball', 'softball', 'sport', 'game'],
    ['🎾', 'tennis', 'tennis', 'sport', 'racket'],
    ['🏐', 'volleyball', 'volleyball', 'sport', 'game'],
    ['🏉', 'rugby football', 'rugby', 'sport', 'game'],
    ['🥏', 'flying disc', 'frisbee', 'sport', 'disc'],
    ['🎱', 'pool 8 ball', 'billiards', 'pool', 'game'],
    ['🏓', 'ping pong', 'table tennis', 'sport', 'game'],
    ['🏸', 'badminton', 'badminton', 'sport', 'racket'],
    ['🥊', 'boxing glove', 'boxing', 'fight', 'sport'],
    ['🥋', 'martial arts uniform', 'karate', 'martial arts', 'sport'],
    ['⛳', 'flag in hole', 'golf', 'sport', 'course'],
    ['⛸️', 'ice skate', 'skate', 'winter sport', 'ice'],
    ['🎣', 'fishing pole', 'fishing', 'sport', 'water'],
    ['🤿', 'diving mask', 'scuba', 'diving', 'water'],
    ['🎽', 'running shirt', 'running', 'sport', 'race'],
    ['🎿', 'skis', 'ski', 'winter', 'sport'],
    ['🛷', 'sled', 'sled', 'winter', 'sport'],
    ['🏂', 'snowboarder', 'snowboard', 'winter sport'],
    ['🏋️', 'person lifting weights', 'gym', 'fitness', 'workout'],
    ['🤼', 'people wrestling', 'wrestling', 'sport', 'fight'],
    ['🤸', 'person cartwheeling', 'gymnastics', 'sport', 'move'],
    ['⛹️', 'person bouncing ball', 'basketball', 'sport'],
    ['🤺', 'person fencing', 'fencing', 'sport', 'sword'],
    ['🏇', 'horse racing', 'horse', 'race', 'sport'],
    ['🧘', 'person in lotus position', 'meditation', 'yoga', 'calm'],
    ['🎮', 'video game', 'gaming', 'controller', 'play'],
    ['🕹️', 'joystick', 'arcade', 'game', 'retro'],
    ['🎲', 'game die', 'dice', 'board game', 'luck'],
    ['♟️', 'chess pawn', 'chess', 'strategy', 'game'],
    ['🧩', 'puzzle piece', 'puzzle', 'solve', 'game'],
    ['🎯', 'direct hit', 'target', 'bullseye', 'goal'],
    ['🎳', 'bowling', 'bowling', 'sport', 'game'],
    ['🎰', 'slot machine', 'casino', 'slots', 'luck'],
    ['🎨', 'artist palette', 'art', 'paint', 'creative'],
    ['🎭', 'performing arts', 'theater', 'drama', 'mask'],
    ['🎤', 'microphone', 'singing', 'karaoke', 'music'],
    ['🎧', 'headphone', 'music', 'audio', 'listen'],
    ['🎼', 'musical score', 'music', 'sheet', 'notes'],
    ['🎹', 'musical keyboard', 'piano', 'music', 'instrument'],
    ['🥁', 'drum', 'drums', 'music', 'instrument'],
    ['🎸', 'guitar', 'music', 'instrument', 'rock'],
    ['🎷', 'saxophone', 'music', 'instrument', 'jazz'],
    ['🎺', 'trumpet', 'music', 'instrument', 'brass'],
    ['🎻', 'violin', 'music', 'instrument', 'string'],
  ]),
  ...define('Travel', [
    ['🚗', 'automobile', 'car', 'drive', 'vehicle', 'travel'],
    ['🚕', 'taxi', 'cab', 'car', 'ride'],
    ['🚙', 'sport utility vehicle', 'suv', 'car', 'vehicle'],
    ['🚌', 'bus', 'bus', 'public transport', 'travel'],
    ['🚎', 'trolleybus', 'bus', 'transport', 'city'],
    ['🏎️', 'racing car', 'race', 'car', 'speed'],
    ['🚓', 'police car', 'police', 'car', 'emergency'],
    ['🚑', 'ambulance', 'ambulance', 'medical', 'emergency'],
    ['🚒', 'fire engine', 'fire truck', 'emergency', 'vehicle'],
    ['🚐', 'minibus', 'van', 'vehicle', 'travel'],
    ['🛻', 'pickup truck', 'truck', 'vehicle', 'utility'],
    ['🚚', 'delivery truck', 'truck', 'shipping', 'delivery'],
    ['🚛', 'articulated lorry', 'truck', 'cargo', 'transport'],
    ['🚜', 'tractor', 'farm', 'vehicle', 'agriculture'],
    ['🏍️', 'motorcycle', 'motorbike', 'bike', 'vehicle'],
    ['🛵', 'motor scooter', 'scooter', 'vehicle', 'ride'],
    ['🚲', 'bicycle', 'bike', 'cycling', 'ride'],
    ['🛴', 'kick scooter', 'scooter', 'ride', 'street'],
    ['🚏', 'bus stop', 'bus stop', 'transport', 'station'],
    ['🛣️', 'motorway', 'highway', 'road', 'travel'],
    ['🛤️', 'railway track', 'train tracks', 'rail', 'travel'],
    ['🚦', 'vertical traffic light', 'traffic', 'signal', 'road'],
    ['🛑', 'stop sign', 'stop', 'traffic', 'road'],
    ['🚧', 'construction', 'roadwork', 'warning', 'barrier'],
    ['⚓', 'anchor', 'ship', 'boat', 'sea'],
    ['⛵', 'sailboat', 'boat', 'sailing', 'sea'],
    ['🛶', 'canoe', 'boat', 'water', 'travel'],
    ['🚤', 'speedboat', 'boat', 'water', 'fast'],
    ['🛳️', 'passenger ship', 'ship', 'cruise', 'boat'],
    ['⛴️', 'ferry', 'boat', 'ship', 'transport'],
    ['🚢', 'ship', 'boat', 'ocean', 'travel'],
    ['✈️', 'airplane', 'plane', 'flight', 'travel'],
    ['🛩️', 'small airplane', 'plane', 'flight', 'travel'],
    ['🛫', 'airplane departure', 'flight', 'takeoff', 'airport'],
    ['🛬', 'airplane arrival', 'flight', 'landing', 'airport'],
    ['🪂', 'parachute', 'skydiving', 'air', 'sport'],
    ['💺', 'seat', 'airline seat', 'travel', 'chair'],
    ['🚁', 'helicopter', 'heli', 'air', 'travel'],
    ['🚂', 'locomotive', 'train', 'rail', 'transport'],
    ['🚆', 'train', 'railway', 'transport', 'travel'],
    ['🚇', 'metro', 'subway', 'train', 'city'],
    ['🚉', 'station', 'train station', 'rail', 'travel'],
    ['🚊', 'tram', 'tram', 'city transport', 'rail'],
    ['🚝', 'monorail', 'train', 'transport', 'rail'],
    ['🚞', 'mountain railway', 'train', 'mountain', 'travel'],
    ['🚋', 'tram car', 'tram', 'city', 'transport'],
    ['🗺️', 'world map', 'map', 'travel', 'navigation'],
    ['🧭', 'compass', 'navigation', 'direction', 'travel'],
    ['🏔️', 'snow-capped mountain', 'mountain', 'nature', 'travel'],
    ['🏝️', 'desert island', 'island', 'beach', 'vacation'],
  ]),
  ...define('Objects', [
    ['⌚', 'watch', 'watch', 'time', 'clock'],
    ['📱', 'mobile phone', 'phone', 'smartphone', 'device'],
    ['📲', 'mobile phone with arrow', 'phone', 'incoming', 'call'],
    ['💻', 'laptop', 'computer', 'work', 'device'],
    ['⌨️', 'keyboard', 'keyboard', 'computer', 'typing'],
    ['🖥️', 'desktop computer', 'computer', 'desktop', 'pc'],
    ['🖨️', 'printer', 'printer', 'office', 'paper'],
    ['🖱️', 'computer mouse', 'mouse', 'computer', 'click'],
    ['🖲️', 'trackball', 'trackball', 'computer', 'device'],
    ['🧮', 'abacus', 'calculator', 'math', 'count'],
    ['🎥', 'movie camera', 'camera', 'video', 'film'],
    ['📷', 'camera', 'photo', 'picture', 'lens'],
    ['📸', 'camera with flash', 'photo', 'camera', 'flash'],
    ['📹', 'video camera', 'video', 'camera', 'record'],
    ['📼', 'videocassette', 'vhs', 'tape', 'retro'],
    ['🔍', 'magnifying glass tilted left', 'search', 'find', 'zoom'],
    ['🔎', 'magnifying glass tilted right', 'search', 'find', 'zoom'],
    ['🕯️', 'candle', 'candle', 'light', 'wax'],
    ['💡', 'light bulb', 'idea', 'light', 'inspiration'],
    ['🔦', 'flashlight', 'torch', 'light', 'dark'],
    ['🏮', 'red paper lantern', 'lantern', 'light', 'festival'],
    ['🪔', 'diya lamp', 'lamp', 'light', 'festival'],
    ['📔', 'notebook with decorative cover', 'notebook', 'notes', 'book'],
    ['📕', 'closed book', 'book', 'read', 'study'],
    ['📖', 'open book', 'book', 'read', 'study'],
    ['📗', 'green book', 'book', 'read', 'study'],
    ['📘', 'blue book', 'book', 'read', 'study'],
    ['📙', 'orange book', 'book', 'read', 'study'],
    ['📚', 'books', 'books', 'library', 'study'],
    ['📓', 'notebook', 'notes', 'book', 'write'],
    ['📒', 'ledger', 'accounting', 'book', 'notes'],
    ['📃', 'page with curl', 'document', 'page', 'file'],
    ['📄', 'page facing up', 'document', 'paper', 'file'],
    ['📰', 'newspaper', 'news', 'paper', 'media'],
    ['📑', 'bookmark tabs', 'tabs', 'document', 'index'],
    ['🔖', 'bookmark', 'bookmark', 'save', 'mark'],
    ['🏷️', 'label', 'tag', 'price', 'sticker'],
    ['💰', 'money bag', 'money', 'cash', 'wealth'],
    ['🪙', 'coin', 'money', 'cash', 'currency'],
    ['💳', 'credit card', 'card', 'payment', 'bank'],
    ['💎', 'gem stone', 'diamond', 'gem', 'jewel'],
    ['⚖️', 'balance scale', 'justice', 'law', 'scale'],
    ['🔧', 'wrench', 'tool', 'fix', 'repair'],
    ['🔨', 'hammer', 'tool', 'build', 'repair'],
    ['🛠️', 'hammer and wrench', 'tools', 'build', 'repair'],
    ['⛏️', 'pick', 'tool', 'mine', 'dig'],
    ['🪓', 'axe', 'tool', 'chop', 'wood'],
    ['🪚', 'carpentry saw', 'saw', 'tool', 'woodwork'],
    ['⚙️', 'gear', 'settings', 'config', 'system'],
    ['🧰', 'toolbox', 'tools', 'repair', 'kit'],
    ['🧲', 'magnet', 'magnet', 'science', 'metal'],
    ['🧪', 'test tube', 'science', 'lab', 'experiment'],
    ['🧫', 'petri dish', 'science', 'lab', 'biology'],
    ['🧬', 'dna', 'science', 'genetics', 'biology'],
    ['🔬', 'microscope', 'science', 'lab', 'research'],
    ['🔭', 'telescope', 'space', 'science', 'observe'],
    ['📡', 'satellite antenna', 'signal', 'broadcast', 'communication'],
    ['💉', 'syringe', 'medicine', 'vaccine', 'health'],
    ['🩺', 'stethoscope', 'doctor', 'medical', 'health'],
    ['🚪', 'door', 'door', 'entry', 'exit'],
    ['🪑', 'chair', 'chair', 'furniture', 'seat'],
    ['🛏️', 'bed', 'sleep', 'furniture', 'rest'],
    ['🛋️', 'couch and lamp', 'sofa', 'living room', 'furniture'],
    ['🚽', 'toilet', 'bathroom', 'wc', 'restroom'],
    ['🧻', 'roll of paper', 'toilet paper', 'paper', 'bathroom'],
    ['🪞', 'mirror', 'mirror', 'reflection', 'glass'],
  ]),
  ...define('Symbols', [
    ['✅', 'check mark button', 'check', 'done', 'success', 'ok', 'yes'],
    ['☑️', 'check box with check', 'checkbox', 'check', 'selected'],
    ['✔️', 'check mark', 'check', 'tick', 'yes', 'correct'],
    ['✖️', 'multiply', 'x', 'close', 'cancel', 'wrong'],
    ['❌', 'cross mark', 'x', 'no', 'close', 'error'],
    ['❎', 'cross mark button', 'x', 'cancel', 'no'],
    ['➕', 'plus', 'plus', 'add', 'math'],
    ['➖', 'minus', 'minus', 'subtract', 'math'],
    ['➗', 'divide', 'divide', 'math', 'split'],
    ['➰', 'curly loop', 'loop', 'repeat', 'swirl'],
    ['➿', 'double curly loop', 'loop', 'repeat', 'swirl'],
    ['⭕', 'hollow red circle', 'circle', 'mark', 'target'],
    ['🔴', 'red circle', 'red', 'dot', 'record'],
    ['🟠', 'orange circle', 'orange', 'dot', 'indicator'],
    ['🟡', 'yellow circle', 'yellow', 'dot', 'indicator'],
    ['🟢', 'green circle', 'green', 'dot', 'online'],
    ['🔵', 'blue circle', 'blue', 'dot', 'indicator'],
    ['🟣', 'purple circle', 'purple', 'dot', 'indicator'],
    ['⚫', 'black circle', 'black', 'dot', 'indicator'],
    ['⚪', 'white circle', 'white', 'dot', 'indicator'],
    ['🟥', 'red square', 'red', 'square', 'shape'],
    ['🟩', 'green square', 'green', 'square', 'shape'],
    ['🟦', 'blue square', 'blue', 'square', 'shape'],
    ['🟨', 'yellow square', 'yellow', 'square', 'shape'],
    ['🟧', 'orange square', 'orange', 'square', 'shape'],
    ['🟪', 'purple square', 'purple', 'square', 'shape'],
    ['⬛', 'black large square', 'black', 'square', 'shape'],
    ['⬜', 'white large square', 'white', 'square', 'shape'],
    ['⭐', 'star', 'star', 'favorite', 'highlight', 'rating'],
    ['🌟', 'glowing star', 'star', 'sparkle', 'special'],
    ['✨', 'sparkles', 'sparkle', 'magic', 'shiny', 'clean'],
    ['⚡', 'high voltage', 'lightning', 'electric', 'fast', 'energy'],
    ['🔥', 'fire', 'fire', 'hot', 'lit', 'cool', 'trending'],
    ['💥', 'collision', 'boom', 'explosion', 'impact'],
    ['💫', 'dizzy', 'sparkle', 'star', 'magic'],
    ['💦', 'sweat droplets', 'water', 'splash', 'drops'],
    ['💨', 'dashing away', 'fast', 'speed', 'wind'],
    ['🕳️', 'hole', 'hole', 'empty', 'void'],
    ['💬', 'speech balloon', 'chat', 'message', 'talk'],
    ['🗨️', 'left speech bubble', 'speech', 'chat', 'message'],
    ['🗯️', 'right anger bubble', 'anger', 'comic', 'mad'],
    ['💭', 'thought balloon', 'thought', 'thinking', 'idea'],
    ['💤', 'zzz', 'sleep', 'tired', 'snore'],
    ['🚨', 'police car light', 'alert', 'emergency', 'siren'],
    ['🔔', 'bell', 'notification', 'alert', 'ring'],
    ['🔕', 'bell with slash', 'mute', 'notifications off', 'silent'],
    ['📣', 'megaphone', 'announce', 'loud', 'broadcast'],
    ['🔈', 'speaker low volume', 'volume', 'sound', 'audio'],
    ['🔉', 'speaker medium volume', 'volume', 'sound', 'audio'],
    ['🔊', 'speaker high volume', 'volume', 'sound', 'audio', 'loud'],
    ['🔇', 'muted speaker', 'mute', 'silent', 'audio off'],
    ['♻️', 'recycling symbol', 'recycle', 'eco', 'green'],
    ['⚠️', 'warning', 'warning', 'caution', 'alert'],
    ['🚫', 'prohibited', 'no', 'forbidden', 'ban', 'stop'],
    ['⛔', 'no entry', 'stop', 'forbidden', 'no'],
    ['🔞', 'no one under eighteen', '18+', 'adult', 'age'],
    ['📵', 'no mobile phones', 'no phone', 'forbidden', 'rule'],
    ['❗', 'red exclamation mark', 'exclamation', 'important', 'alert'],
    ['❓', 'red question mark', 'question', 'help', 'unknown'],
    ['‼️', 'double exclamation mark', 'alert', 'important', 'urgent'],
    ['⁉️', 'exclamation question mark', 'what', 'confused', 'question'],
    ['🔁', 'repeat button', 'repeat', 'loop', 'again'],
    ['🔂', 'repeat single button', 'repeat one', 'loop', 'song'],
    ['▶️', 'play button', 'play', 'start', 'media'],
    ['⏸️', 'pause button', 'pause', 'stop', 'media'],
    ['⏹️', 'stop button', 'stop', 'media', 'end'],
    ['⏭️', 'next track button', 'next', 'skip', 'media'],
    ['⏮️', 'last track button', 'previous', 'back', 'media'],
    ['🔀', 'shuffle tracks button', 'shuffle', 'random', 'music'],
    ['🔚', 'end arrow', 'end', 'finish', 'arrow'],
    ['🔙', 'back arrow', 'back', 'return', 'arrow'],
    ['🔛', 'on arrow', 'on', 'switch', 'arrow'],
    ['🔝', 'top arrow', 'top', 'up', 'arrow'],
    ['🛐', 'place of worship', 'religion', 'prayer', 'faith'],
    ['♈', 'aries', 'zodiac', 'astrology', 'sign'],
    ['♉', 'taurus', 'zodiac', 'astrology', 'sign'],
    ['♊', 'gemini', 'zodiac', 'astrology', 'sign'],
  ]),
  ...define('Flags', [
    ['🏳️', 'white flag', 'flag', 'surrender', 'truce'],
    ['🏴', 'black flag', 'flag', 'pirate', 'dark'],
    ['🏁', 'chequered flag', 'finish', 'race', 'flag'],
    ['🚩', 'triangular flag', 'flag', 'marker', 'location'],
    ['🏳️‍🌈', 'rainbow flag', 'pride', 'lgbtq', 'rainbow', 'flag'],
    ['🏳️‍⚧️', 'transgender flag', 'trans', 'pride', 'flag'],
    ['🇺🇸', 'flag united states', 'usa', 'us', 'america', 'flag'],
    ['🇬🇧', 'flag united kingdom', 'uk', 'britain', 'england', 'flag'],
    ['🇨🇦', 'flag canada', 'canada', 'ca', 'flag'],
    ['🇩🇪', 'flag germany', 'germany', 'de', 'flag'],
    ['🇫🇷', 'flag france', 'france', 'fr', 'flag'],
    ['🇪🇸', 'flag spain', 'spain', 'es', 'flag'],
    ['🇮🇹', 'flag italy', 'italy', 'it', 'flag'],
    ['🇯🇵', 'flag japan', 'japan', 'jp', 'flag'],
    ['🇰🇷', 'flag south korea', 'korea', 'kr', 'flag'],
    ['🇨🇳', 'flag china', 'china', 'cn', 'flag'],
    ['🇮🇳', 'flag india', 'india', 'in', 'flag'],
    ['🇰🇿', 'flag kazakhstan', 'kazakhstan', 'kz', 'flag'],
    ['🇧🇷', 'flag brazil', 'brazil', 'br', 'flag'],
    ['🇦🇺', 'flag australia', 'australia', 'au', 'flag'],
    ['🇳🇿', 'flag new zealand', 'new zealand', 'nz', 'flag'],
    ['🇲🇽', 'flag mexico', 'mexico', 'mx', 'flag'],
    ['🇹🇷', 'flag turkey', 'turkey', 'tr', 'flag'],
    ['🇺🇦', 'flag ukraine', 'ukraine', 'ua', 'flag'],
    ['🇵🇱', 'flag poland', 'poland', 'pl', 'flag'],
    ['🇸🇪', 'flag sweden', 'sweden', 'se', 'flag'],
    ['🇳🇴', 'flag norway', 'norway', 'no', 'flag'],
    ['🇫🇮', 'flag finland', 'finland', 'fi', 'flag'],
    ['🇳🇱', 'flag netherlands', 'netherlands', 'nl', 'flag'],
    ['🇨🇭', 'flag switzerland', 'switzerland', 'ch', 'flag'],
  ]),
]
